[package]
name = "assignement-6-q1"
version = "0.1.0"
authors = ["glowsol <zahid@glowsol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
